export { default as Navbar} from './navBar/navbar'
export { default as Feature } from './feature/feature'
export { default as PortfolioCard } from './portfolioCard/PortfolioCard'
export { default as ClientCard } from './clientCard/ClientCard' 
export { default as ClientFeature } from './clientFeature/clientFeature'